galaxy_info:
  author: Andrew Savchenko
  description: Dotfiles setup
  company: stoptracking.net

  issue_tracker_url: https://github.com/savchenko/debian/issues
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - stretch
        - buster

  galaxy_tags:
    - dotfiles
    - neovim
    - tmux
    - bash

dependencies: []
