---
- hosts: virtbsy
  tasks:

  - name: Execute `base` role
    include_role:
      name: base
      apply:
        tags:
          # Limit play via `ansible-playbook --tags role_*`
          - role_base
    tags:
      # `always` is a keyword here, not a tag.
      - always
    vars:
      # Refer to the respective READMEs for variables' descriptions and default values
      allow_reboot: true
      allow_ssh: true
      debs: []
      disable_bluetooth: true
      disable_firewire: true
      disable_hfs_udf: true
      disable_speaker: true
      disable_thunderbolt: true
      fb_font_size: 10x18
      fstab_noexec: true
      generate_moduli: false
      grub_optional: ""
      locale: en_US.UTF8
      resolver_blocklist: ""
      resolver_listen_on_ip: 127.0.0.1
      resolver_primary_hostname: dns.quad9.net
      resolver_primary_ip: 9.9.9.9
      resolver_secondary_hostname: dns.quad9.net
      resolver_secondary_ip: 149.112.112.112
      resolver_tls: true
      set_capslock: false
      set_hostname: true
      sshd_less_secure: false
      sshguard_install: false
      sshguard_path: /etc/sshguard/sshguard.conf
      timezone: Australia/Adelaide
      ufw_rule:
        - { comment: 'Drop incoming TCP traffic from 172.16.17.92 to port 22', direction: 'in', from: '172.16.17.92', port: '22', proto: 'tcp', rule: 'deny' }
        - { comment: 'Allow all traffic from 192.168.122.*', direction: 'in', from: '192.168.122.0/16', port: '1:65000', proto: 'tcp', rule: 'allow' }
      ufw_service:
        - { comment: 'Reject Yahoo messenger from 192.168.67.83', rule: 'deny', from: '192.168.67.83', service: 'Yahoo' }


  - name: Execute `dotfiles` role
    include_role:
      name: dotfiles
      apply:
        tags:
          - role_dotfiles
    tags:
      - always
    vars:
      change_tmux_prefix: true
      copy_dotfiles: true
      link_to_localhost: false
      remote_bash_emacs: false
      remote_gitconfig: true
      setup_neovim: true

  - name: Execute `wireguard` role
    include_role:
      name: wireguard
      apply:
        tags:
          - role_wireguard
    tags:
      - always
    vars:
      wg_autostart: true
      wg_clients:
        - { name: 'ClientA', pubkey: 'WC5a0cSWATZwLsQH1REjGcQsomZyEtRTaAqyRK20emY=', psk: 'yKsg+u7zY9N5rjgR3YE6cSu90aFBpxEPA3uKzK9vJc0=', ip: '192.168.2.1.20', keepalive: '0' }
        - { name: 'ClientB', pubkey: 'qOwMjZuaVjfmdCSoOQbTp8MPADN+yB5gjRAmddA7jUM=', psk: 'Fo1UMMLxbyPiYwrJ/vE7tqPa66gblskjIc5xyQPsXgg=', ip: '192.168.2.1.30', keepalive: '33' }
      wg_forward: true
      wg_iface: wg5
      wg_overwrite: true
      wg_peerkey: wIZPnbsM9lto1MSD2J.22.gbIsSHmp1LFu96IGX2310=
      wg_port: 51820
      wg_server_ip: 192.168.2.1.1
      wg_server_subnet: '192.168.2.1.0/24'
      wg_start: true
      wg_systemd: true

  - name: Execute `transfer-agent` role
    include_role:
      name: transfer-agent
      apply:
        tags:
          - role_transfer
    tags:
      - always
    vars:
      agent_group: agents
      agent_name: xfer_agent
      pubkey_from_current_user: true
      remove_existing_user: true
      add_rsync: true
    when: false
