---
- hosts: localhost
  tasks:

  - name: Execute `base` role
    include_role:
      name: base
      apply:
        tags:
          # Limit play via `ansible-playbook --tags role_*`
          - role_base
    tags:
      # `always` is a keyword here, not a tag.
      - always
    vars:
      # Refer to the respective READMEs for variables' descriptions and default values
      allow_reboot: false
      allow_ssh: false
      debs: []
      disable_bluetooth: true
      disable_firewire: true
      disable_hfs_udf: true
      disable_speaker: false
      disable_thunderbolt: true
      fb_font_size: 10x18
      fstab_noexec: true
      generate_moduli: false
      grub_optional: ""
      locale: en_US.UTF8
      resolver_blocklist: ""
      resolver_listen_on_ip: 127.0.0.1
      resolver_primary_hostname: dns.quad9.net
      resolver_primary_ip: 9.9.9.9
      resolver_secondary_hostname: dns.quad9.net
      resolver_secondary_ip: 149.112.112.112
      resolver_tls: false
      set_capslock: true
      set_hostname: false
      sshd_less_secure: false
      sshguard_path: /etc/sshguard/sshguard.conf
      timezone: Australia/Adelaide

  - name: Execute `dotfiles` role
    include_role:
      name: dotfiles
      apply:
        tags:
          - role_dotfiles
    tags:
      - always
    vars:
      change_tmux_prefix: false
      copy_dotfiles: false
      link_to_localhost: true
      remote_bash_emacs: false
      remote_gitconfig: false
      setup_neovim: true

  - name: Execute `transfer-agent` role
    include_role:
      name: transfer-agent
      apply:
        tags:
          - role_transfer
    tags:
      - always
    vars:
      agent_group: agents
      agent_name: xfer_agent
      pubkey_from_current_user: true
      remove_existing_user: true
      add_rsync: true
    when: false # this block won't run

  - name: Execute `laptop` role
    include_role:
      name: laptop
      apply:
        tags:
          - role_laptop
    tags:
      - always
    vars:
      alsa_out_card: 3
      alsa_out_device: 0
      alsa_setup: true
      enable_sleep_hibernate: true
      intel_disable_igfx: false
      intel_hda_options: ["model=thinkpad", "power_save_controller=Y"]
      systemd_units_disable: ['systemd-backlight@backlight:acpi_video0.service', 'tor@default.service', 'tor.service']
      systemd_units_enable: []
      logind_hibernate_delay: 900
      logind_idle_action: suspend-then-hibernate
      logind_idle_time: 600
      logind_lid_action: suspend-then-hibernate
      logind_powerbutton_action: poweroff
      user_add_i2c: true
      virtio_network_autostart: true
      virtio_use_default_network: true
