---
- name: Add tmux.conf to the list of dotfiles, no prefix change
  set_fact:
    dotfiles_list: "{{ dotfiles_list | union(dotfiles_list_tmux) }}"
  when: not change_tmux_prefix

- name: Add local .gitconfig to the list of dotfiles
  set_fact:
    dotfiles_list: "{{ dotfiles_list | union(dotfiles_gitconfig_local) }}"
  when: not remote_gitconfig

- name: Add remote .gitconfig to the list of dotfiles
  set_fact:
    dotfiles_list: "{{ dotfiles_list | union(dotfiles_gitconfig_remote) }}"
  when: remote_gitconfig

  #
  # `copy_dotfiles`
  #
- block:

  - name: Create remote dotfiles folders tree
    file:
      path: "{{ ansible_env.HOME }}/.local/etc/dotfiles"
      state: directory

  - name: Copy primary dotfiles to the remote machine
    copy:
      src: "{{ item.src }}"
      dest: "{{ ansible_env.HOME }}/.local/etc/dotfiles/{{ item.src }}"
    with_items: "{{ dotfiles_list }}"

  - name: Link dotfiles from ~/.local/etc/dotfiles to $HOME
    become: yes
    become_user: "{{ ansible_env.USER }}"
    file:
      src: "{{ ansible_env.HOME }}/.local/etc/dotfiles/{{ item.src }}"
      dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
      state: link
      force: yes
    with_items: "{{ dotfiles_list }}"
    register: dotfiles_linked

  - name: Copy ~/.local/bin
    copy:
      src: bin/
      dest: ~/.local/bin

  when: copy_dotfiles

  #
  # Link from this role
  #
- name: Link dotfiles from this role to $HOME
  file:
    src: "{{role_path}}/files/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ dotfiles_list }}"
  when: link_to_localhost and not WSL1 and not copy_dotfiles
  register: dotfiles_linked

- name: Link ~/.local/bin from this role to $HOME
  file:
    src: "{{role_path}}/files/bin"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    state: link
    force: yes
  when: link_to_localhost and not WSL1 and not copy_dotfiles
