---
- name: Checking the logic
  assert:
    that:
      - copy_dotfiles != link_to_localhost
    fail_msg: "Copying to remote host from controller and simultaneously trying to link from this role dosn't make sense.\nChoose one"

- name: Hush login, setup terminfo and ~/.ssh
  import_tasks: dotfiles_init.yml
  tags:
    - dotfiles_init

- name: Backup existing dotfiles
  import_tasks: dotfiles_backup.yml
  tags:
    - dotfiles_backup

- name: Link dotfiles to $HOME
  import_tasks: dotfiles_link.yml
  tags:
    - dotfiles_link

- name: Adapt dotfiles for a remote host
  import_tasks: dotfiles_remote.yml
  tags:
    - dotfiles_remote

- name: Setup NeoVim
  import_tasks: dotfiles_neovim.yml
  when: neovim == true
  tags:
    - dotfiles_neovim
