#
# TL;DR:
#
#     ~/.bash_profile should be super-simple and just load .profile and .bashrc (in that order)
#     ~/.profile has the stuff NOT specifically related to bash, such as environment variables (PATH and friends)
#     ~/.bashrc has anything you'd want at an interactive command line. Command prompt, EDITOR variable, bash aliases for my use
#

if [ -r ~/.profile ]; then . ~/.profile; fi
if [ "$BASH" ] && [ -r ~/.bashrc ]; then . ~/.bashrc; fi
