" ----------------------------------------------------------------------------
" Plugins
" ----------------------------------------------------------------------------
 
" Polyglot, must be here unfortunately
let g:polyglot_disabled = ['sensible', 'html']
 
call plug#begin('~/.vim/plugged')
 
Plug 'https://github.com/stoptracking-vim/clever-f.vim'
Plug 'https://github.com/stoptracking-vim/fzf'
Plug 'https://github.com/stoptracking-vim/fzf.vim'
Plug 'https://github.com/stoptracking-vim/fzy.vim'
Plug 'https://github.com/stoptracking-vim/indentLine'
Plug 'https://github.com/stoptracking-vim/nerdcommenter'
Plug 'https://github.com/stoptracking-vim/nerdtree'
Plug 'https://github.com/stoptracking-vim/vim-airline'
Plug 'https://github.com/stoptracking-vim/vim-airline-themes'
Plug 'https://github.com/stoptracking-vim/vim-autoread'
Plug 'https://github.com/stoptracking-vim/vim-easymotion'
Plug 'https://github.com/stoptracking-vim/vim-gitgutter'
Plug 'https://github.com/stoptracking-vim/vim-lastplace'
Plug 'https://github.com/stoptracking-vim/vim-matchquote'
Plug 'https://github.com/stoptracking-vim/vim-plug'
Plug 'https://github.com/stoptracking-vim/vim-polyglot'
Plug 'https://github.com/stoptracking-vim/vim-startify'
Plug 'https://github.com/stoptracking-vim/vim-surround'
Plug 'https://github.com/stoptracking-vim/vim-table-mode'
Plug 'https://github.com/stoptracking-vim/vim-visual-multi'
Plug 'https://github.com/stoptracking-vim/vim-zoom'
Plug 'https://github.com/stoptracking-vim/supertab'
Plug 'https://github.com/stoptracking-vim/pear-tree'
Plug 'https://github.com/stoptracking-vim/vim-lion'
Plug 'https://github.com/stoptracking-vim/vim-fugitive'

call plug#end()



" ----------------------------------------------------------------------------
" System
" ----------------------------------------------------------------------------

" Basics
set ttyfast
set nocompatible
set lazyredraw
set shell=/bin/bash
set modelines=0
set termencoding=utf-8
set encoding=utf8
set fileformat=unix
set clipboard=unnamedplus
filetype plugin on

" Write swap every 0.5s if nothing is typed and report CursorHold
set updatetime=25

" Intendation
filetype indent on
set autoindent
set smartindent

" Backspace over intendation, EOL and outside of current insert
set backspace=indent,eol,start

" Menu next to the airline
set wildmenu
set wildignore+=.git,.hg,.svn
set wildmode=longest:full,full
set wildignore+=*.aux,*.out,*.toc
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest,*.rbc,*.class,*.pyc
set wildignore+=*.ai,*.bmp,*.gif,*.ico,*.jpg,*.jpeg,*.png,*.psd,*.webp
set wildignore+=*.avi,*.divx,*.mp4,*.webm,*.mov,*.m2ts,*.mkv,*.vob,*.mpg,*.mpeg
set wildignore+=*.mp3,*.oga,*.ogg,*.wav,*.flac
set wildignore+=*.eot,*.otf,*.ttf,*.woff
set wildignore+=*.doc,*.pdf,*.cbr,*.cbz
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz,*.kgb
set wildignore+=*.swp,.lock,.DS_Store,._*

" Leave it, needed for regexp
set magic

" Window's title (i3 tab for example)
set title

" Enable mouse with tmux 2.4
set mouse=a

" Allow switching buffers w/o saving
set hidden

" Don't join spaces on paste
set nojoinspaces

" Don't autoextend comments or join comment characters
set formatoptions-=r formatoptions-=c formatoptions-=o formatoptions-=j

" Autosaves
if has("unix")
  set backupdir=~/.vim/backup
  set directory=~/.vim/tmp
  set undodir=~/.vim/undo
elseif has("win32")
  let g:nv_dir=substitute($HOME, '\\', '\\\', "g").'\\AppData\\Local\\nvim\\'
  execute "set backupdir=".g:nv_dir.'backup'
  execute "set directory=".g:nv_dir.'tmp'
  execute "set undodir=".g:nv_dir.'undo'
endif
set backup
set undofile
set noswapfile
set undolevels=1000
set undoreload=10000
set history=1000

" NetRW
let g:netrw_banner = 0
let g:netrw_browse_split = 3
let g:netrw_liststyle = 3
let g:netrw_winsize = 20

" Highlight brackets
set showmatch

" Search is incremental and case-sensitive if UpperCase is present
set ignorecase
set smartcase
set hlsearch
set incsearch

" <TAB> at the ^ equals to 'shiftwidth'
set smarttab

" Round indent to multiple of 'shiftwidth`
set shiftround

" Expand <TAB> into spaces
set expandtab

" reveal already opened files instead of opening new buffers
set switchbuf=useopen,usetab,newtab

" Nerd commenter
let NERDSpaceDelims=1
let g:NERDCompactSexyComs = 1
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 0
let g:NERDToggleCheckAllLines = 1


" ----------------------------------------------------------------------------
" Visuals
" ----------------------------------------------------------------------------

" Highlight up to 512 chars per line
set synmaxcol=512

" Attempt to show 24-bit palette with 256 colours fallback
if has("termguicolors")
    set termguicolors
else
    set t_Co=256
endif

" BG and italics colour fix for tmux
if &term =~# '^screen'
    set t_ut=
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set t_ZH=^[[3m
    set t_ZR=^[[23m
endif

" Colorscheme
let g:github_colors_soft = 1
let g:github_colors_block_diffmark = 1
let g:enable_bold_font = 1
let g:enable_italic_font = 1
let g:hybrid_transparent_background = 1
let g:hybrid_hy2 = 1
colorscheme better_hybrid
syntax on

" Nice highlight of the current line, turned off by  default
highlight CursorLine cterm=NONE ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE
set cul

" Don't show typed command, causes glitches in SR-bottom corner, do not show mode
set noshowcmd
set noshowmode

" Line numbers by default
set number

" Don't show startup message
set shortmess+=Ic

" Wrap long lines and don't break words
set wrap
set linebreak

" indent wrapped lines, by...
set breakindent
set breakindentopt=shift:2,sbr
set showbreak=↪

" Better vertical split visualization
set fillchars+=vert:\┃

" Natural splits
set splitbelow
set splitright

" Split vertical by default
set diffopt+=vertical

" Disable all bells and don't blink with the cursor
set noerrorbells
set novisualbell
set vb t_vb=
set guicursor=a:blinkon0

" Always show airline
set laststatus=2

" Completion options, don't show preview window with additional information,
" show completion menu even if there is one option available,
" don't insert text until explicitly asked to.
set completeopt-=preview
set completeopt+=menuone
set completeopt+=noinsert,noselect

" Automatically show signcolumn and try to accommodate up to 6 sections
if has('nvim-0.4.0')
  set signcolumn=auto:6
elseif has('nvim-0.3.4') || has('signs')
  set signcolumn=auto
endif

" Change cursor shape
set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor

" Fallback, just in case `guicursor` above does not work
if $TERM == "tmux-256color"
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_SR = "\<Esc>]50;CursorShape=2\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
else
  let &t_SI = "\<Esc>[6 q"
  let &t_SR = "\<Esc>[4 q"
  let &t_EI = "\<Esc>[2 q"
endif

" Invisible characters
set listchars=tab:▸\ ,nbsp:␣,trail:·,eol:¶,space:·,conceal:·

" ----------------------------------------------------------------------------
" Hotkeys
" ----------------------------------------------------------------------------

" F1 switches paste mode
map <silent> <F1> :set nopaste! paste?<cr>
set pastetoggle=<F1>

" Tree
nnoremap <F2> :NERDTreeToggle<cr>

" F3 yanks all
map <F3> :%y+<cr>

" Line numbers
map <silent> <F4> :set nonumber!<cr>

" Toggle indentation
map <F5> :IndentLinesToggle<cr>

" Toggle invisible chars
map <silent> <F6> :set list!<cr>

" Toggle spell-check
map <silent> <F7> :set spell!<cr>

" Go back into normal mode by `ii`
inoremap ii <esc>

" Remap leader from `\` to `Space`
let mapleader = "\<Space>"

" <leader>+sm toggles "scroll mode"
map <leader>sm :call ToggleScrollMode()<cr>

" Insert date header
map <F12> :call DD()<cr>

" Toggle line numbers between absolute/relative
map <S-l> :call ToggleNumber()<cr>

" Save as usual
map <C-s> :w!<CR>
imap <C-s> <Esc>:w!<CR>a

" Close window/split as usual
map <C-w> :close<CR>

" Select all as usual (skips to the last symbol)
map <C-a> <esc>gg0vG$<CR>

" Don't copy result of 'dd', 's' and 'c' into buffer
nnoremap d "_d
vnoremap d "_d
nnoremap s "_s
vnoremap s "_s
nnoremap c "_c
vnoremap c "_c
nnoremap C "_C
vnoremap C "_C

" Move up/down using _visual_ lines (e.g. wrapped ones)
nnoremap j gj
nnoremap k gk
nnoremap <Up> gk
nnoremap <Down> gj

" Add new lines and spaces without changing the mode
nmap <Leader>j mvo<Esc>`v
nmap <Leader>k mvO<Esc>`v
nmap <Leader>h i<space><esc>l
nmap <Leader>l a<space><esc>h

" Save is forced by default (don't nag about "file exists")
map :W<cr> :w!<cr>
map :w<cr> :w!<cr>
map :x<cr> :x!<cr>

" cd into file's directory
map <leader>cd :cd %:p:h<cr>:pwd<cr>

" Don't use Ex mode, exit on QQ
nnoremap Q <nop>
nnoremap QQ ZZ

" Switch splits using Ctrl+hjkl
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Buffer management
nmap <leader>. :bn<CR>
nmap <leader>, :bp<CR>
nmap <leader>q :bp <BAR> bd #<CR>

" Keep text selected after changing intendation with <>
vnoremap < <gv
vnoremap > >gv

" Change folding levels
nmap z1 :set foldlevel=0<CR>
nmap z2 :set foldlevel=1<CR>
nmap z3 :set foldlevel=2<CR>
nmap z4 :set foldlevel=3<CR>

" Move to another line with arrow keys
set whichwrap+=<,>

" Resize splits with +-
if bufwinnr(1)
    map + <C-W>+
    map - <C-W>-
endif

" Move a line of text using Shift+[jk]
nmap <S-j> mz:m+<cr>`z
nmap <S-k> mz:m-2<cr>`z
vmap <S-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <S-k> :m'<-2<cr>`>my`<mzgv`yo`z

" CTRL+V in insert mode
inoremap <C-V> <C-r>+

" CTRL+Z in insert mode
inoremap <C-Z> <Esc>ui

" Enable <S-TAB> to reduce intendation
nnoremap <S-Tab> <<
inoremap <S-Tab> <C-d>

" make n always search forward and N backward
nnoremap <expr> n 'Nn'[v:searchforward]
nnoremap <expr> N 'nN'[v:searchforward]

" make ; always `find` forward and , backward
nnoremap <expr> ; getcharsearch().forward ? ';' : ','
nnoremap <expr> , getcharsearch().forward ? ',' : ';'

" Make jumps L-to-R
nnoremap <C-i> <C-o>
nnoremap <C-o> <C-i>

" --- Plugins ----------------------------------------------------------------

" Zoom
nmap <Leader>z <Plug>(zoom-toggle)

" <leader>+s is ysW
map <leader>s ysW

" Skip empty lines with multiple cursors
map <leader>se :call SkipEmptyLines()<cr>

" Open fzy or rgrep finders
nnoremap <C-f> :FuzzyOpen<CR>
nnoremap <C-g> :FuzzyGrep<CR>

" GitGutter
let g:gitgutter_map_keys = 0
nmap g] :GitGutterNextHunk<CR>
nmap g[ :GitGutterPrevHunk<CR>
nmap <leader>f :GitGutterFold<CR>
nmap <Leader>p <Plug>(GitGutterPreviewHunk)
nmap <Leader>= <Plug>(GitGutterStageHunk)
nmap <Leader>- <Plug>(GitGutterUndoHunk)

" Easymotion
nmap s <Plug>(easymotion-s2)

" --- Functions --------------------------------------------------------------

" Show highlight groups
nmap <leader>sp :call <SID>SynStack()<CR>

" Clear things
nmap <silent><esc><esc> :noh<cr> :call <SID>ClearThings()<CR>

" ----------------------------------------------------------------------------
" Plugins
" ----------------------------------------------------------------------------

" ansible-vim
let g:ansible_unindent_after_newline = 1
let g:ansible_attribute_highlight = 'ab'
let g:ansible_name_highlight = 'b'
let g:ansible_extra_keywords_highlight = 1
let g:ansible_normal_keywords_highlight = 'Operator'
let g:ansible_with_keywords_highlight = 'Operator'

" vim-startify
let g:startify_custom_header = [
            \ '┌┬┐┬ ┬┬┌┐┌┬┌─ ',
            \ ' │ ├─┤││││├┴┐ ',
            \ ' ┴ ┴ ┴┴┘└┘┴ ┴o',
            \ ]

let g:startify_lists = [
            \ { 'type': 'files', 'header': ['MRU'] },
            \ ]

" vim-airline
let g:airline_minimalist_showmod = 0
let g:airline_theme='minimalist'
let g:airline_powerline_fonts=0
let g:airline_skip_empty_sections = 1
let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#whitespace#enabled = 0
let g:airline_symbols = {}
let g:airline_symbols.linenr = ''
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.branch = '🔗'

function! AirlineInit()
    let g:airline_section_z = airline#section#create('%#__accent_bold#%{zoom#statusline()} %3l%#__restore__#/%L :%3v')
endfunction
autocmd User AirlineAfterInit call AirlineInit()

let g:airline_mode_map = {
            \ '__' : '-',
            \ 'n'  : 'N',
            \ 'i'  : 'I',
            \ 'R'  : 'R',
            \ 'c'  : 'C',
            \ 'v'  : 'V',
            \ 'V'  : 'V',
            \ '' : 'V',
            \ 's'  : 'S',
            \ 'S'  : 'S',
            \ '' : 'S',
            \ }

" Show tabline only if >1 file is open
let g:airline#extensions#tabline#show_buffers=1
let g:airline#extensions#tabline#buffer_min_count=2
let g:airline#extensions#tabline#tab_min_count=2

" Disable buffer type SR
let g:airline#extensions#tabline#show_tab_type=0
let g:airline#extensions#tabline#fnamemod=':t'

" Prettier GiGutter glyphs
let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '•'
let g:gitgutter_sign_removed = '-'
let g:gitgutter_sign_removed_first_line = '-'
let g:gitgutter_sign_modified_removed = '~'

" Disable indent line by default
let g:indentLine_enabled = 0
let g:indentLine_setColors = 1
let g:indentLine_char = '│'
let g:indentLine_leadingSpaceEnabled = 0
let g:indentLine_leadingSpaceChar = '·'

" clever-f
let g:clever_f_smart_case = 1
let g:clever_f_fix_key_direction = 1
let g:clever_f_mark_char_color = 'DiffAdd'

" Smart pairs are enabled by default:
let g:pear_tree_smart_openers = 1
let g:pear_tree_smart_closers = 1
let g:pear_tree_smart_backspace = 1

" multi-cursors
let g:VM_silent_exit = 1

" SuperTAB
let g:SuperTabDefaultCompletionType = "<c-n>"
let g:SuperTabContextDefaultCompletionType = "<c-n>"

" vim-lion (gl/gL alignment)
let g:lion_squeeze_spaces = 1

"
" FZF
"
" [Buffers] Jump to the existing window if possible
let g:fzf_buffers_jump = 1

let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" ----------------------------------------------------------------------------
" Macros
" ----------------------------------------------------------------------------

" Mostly use 2 spaces as <Tab>
autocmd FileType text,markdown,vim,ini,gitconfig,*.yml,shell,bash,sh setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Keep Web documents to 2 spaces as <Tab>
autocmd BufRead,BufNewFile *.htm,*.html,*.css,*.js setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Pythonic tabs are limited to *.py
autocmd Filetype python setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

" Fix YAML intendation
autocmd FileType yaml,toml setlocal ts=2 sts=2 sw=2 expandtab autoindent

" Resize splits when VIM is resized
autocmd VimResized * wincmd =

" Return to last edit position when opening files
autocmd BufReadPost *
  \ if line("'\"") > 1 && line("'\"") <= line("$") && &ft !~# 'commit'
  \ |   exe "normal! g`\""
  \ | endif

" Temporarily hide ruler when in FZF mode
autocmd! FileType fzf set laststatus=0 noshowmode noruler | autocmd BufLeave <buffer> set laststatus=2 showmode ruler

" Scroll mode, keeps cursor centered and horizontally unchanged
function! ToggleScrollMode()
    if exists("s:scroll_mode")
        unmap k
        unmap j
        set startofline
        set virtualedit=""
        unlet s:scroll_mode
        echom "scroll mode OFF"
    else
        nnoremap j <C-e>j
        nnoremap k <C-y>k
        set virtualedit=all
        set nostartofline
        let s:scroll_mode = 1
        echom "scroll mode ON"
    endif
endfunction

" Prevent opening files in NERDTree
autocmd FileType nerdtree let t:nerdtree_winnr = bufwinnr('%')
autocmd BufWinEnter * call PreventBuffersInNERDTree()
function! PreventBuffersInNERDTree()
  if bufname('#') =~ 'NERD_tree' && bufname('%') !~ 'NERD_tree'
    \ && exists('t:nerdtree_winnr') && bufwinnr('%') == t:nerdtree_winnr
    \ && &buftype == '' && !exists('g:launching_fzf')
    let bufnum = bufnr('%')
    close
    exe 'b ' . bufnum
  endif
  if exists('g:launching_fzf') | unlet g:launching_fzf | endif
endfunction
 
" Close NERDTree if it's the only window left
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
 
" Toggle between number and relativenumber
function! ToggleNumber()
    if(&relativenumber == 1)
        set norelativenumber
        set number
    else
        set relativenumber
        set nocul
    endif
endfunc
 
" Skip empty lines with multiple cursors
function! SkipEmptyLines()
  if exists("g:VM_skip_empty_lines")
    if(g:VM_skip_empty_lines == 1)
      let g:VM_skip_empty_lines = 0
      echo "VM: Not skipping empty lines"
    else
      let g:VM_skip_empty_lines = 1
      echo "VM: Skipping empty lines"
    endif
  else
    let g:VM_skip_empty_lines = 1
    echo "VM: Skipping empty lines"
  endif
endfunc

" Strips trailing whitespace at the end of files.
function! WhitespaceStrip()
    " save last search & cursor position
    let _s=@/
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    let @/=_s
    call cursor(l, c)
endfunction

" Insert date header
function! DD()
  let date = strftime('%a %d %b %Y %H:%M')
  let line = "\n====================="
  let out = date . line
  put =out
endfunc

" Show highlight groups
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

" Clear things
function! <SID>ClearThings()
  call clever_f#reset()
  call vm#hard_reset()
endfunc
