#!/bin/bash

# `list_geometry` returns the geometry of the focused of visible windows. You can also get they title
# by setting a second argument to `with_description`. The geometry and the title are seperated by `\t`.
#
# Arguments:
#   $1: `focused` or `visible`
#   $2: `with_description` or nothing
#
# Output examples:
#   - with the `with_description` option:
#      12,43 100x200\tTermite
#   - without the `with_description` option:
#      12,43 100x200
function list_geometry () {
  [ "$2" = with_description ] && local append="\t\(.name)" || local append=
  swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.'$1' and .pid) | "\(.rect.x),\(.rect.y) \(.rect.width)x\(.rect.height)'$append'"'
}

FOCUSED=`list_geometry focused`
CHOICE=`wofi -L 6 -W 200 -b -d -p 'Screenshot' -O 'alphabetical' << EOF
Fullscreen
Region
Focused
4s Fullscreen
4s Region
4s Focused
EOF`

SAVEDIR=${SWAY_INTERACTIVE_SCREENSHOT_SAVEDIR:=~/Desktop/screenshots}
FILENAME="$SAVEDIR/$(date +'%Y-%m-%d-%H%M%S_screenshot.png')"
EXPENDED_FILENAME="${FILENAME/#\~/$HOME}"

case $CHOICE in
    Fullscreen)
        grim "$EXPENDED_FILENAME"
  ;;
    Region)
        grim -g "$(slurp)" "$EXPENDED_FILENAME"
  ;;
    Focused)
        grim -g "$FOCUSED" "$EXPENDED_FILENAME"
  ;;
    "4s Fullscreen")
        sleep 4s && grim "$EXPENDED_FILENAME"; wait
  ;;
    "4s Region")
        sleep 4s && grim -g "$(slurp)" "$EXPENDED_FILENAME"; wait
  ;;
    "4s Focused")
        sleep 4s && grim -g "$FOCUSED" "$EXPENDED_FILENAME"; wait
  ;;
    '')
        # notify-send "Screenshot" "Cancelled"
        exit 0
        ;;
    *)
      GEOMETRY="`echo \"$CHOICE\" | cut -d$'\t' -f1`"
      grim -g "$GEOMETRY" "$EXPENDED_FILENAME"
esac

wl-copy < "$EXPENDED_FILENAME"
notify-send "Screenshot" "File saved as <i>'$FILENAME'</i> and copied to the clipboard." -i "$EXPENDED_FILENAME"
