#!/bin/bash
#
# Based on https://github.com/moverest/sway-interactive-screenshot/blob/master/sway-interactive-screenshot
# MIT
#
# `list_geometry` returns the geometry of the focused of visible windows. You can also get they title
# by setting a second argument to `with_description`. The geometry and the title are seperated by `\t`.
#
# Arguments:
#   $1: `focused` or `visible`
#   $2: `with_description` or nothing
#
# Output examples:
#   - with the `with_description` option:
#      12,43 100x200\tTermite
#   - without the `with_description` option:
#      12,43 100x200
function list_geometry () {
  [ "$2" = with_description ] && local append="\t\(.name)" || local append=
  swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.'$1' and .pid) | "\(.rect.x),\(.rect.y) \(.rect.width)x\(.rect.height)'$append'"'
}

FOCUSED=`list_geometry focused`
CHOICE=`wofi -L 6 -W 200 -b -d -p 'Screenshot' -O 'alphabetical' << EOF
Fullscreen
Region
Focused
4s Fullscreen
4s Region
4s Focused
EOF`

SAVEDIR="$HOME/Desktop/screenshots"
DATE="date +'%d-%b_%H-%M-%S.png'"
FILENAME="$SAVEDIR/$(eval $DATE)"

case $CHOICE in
    Fullscreen)
        grim "$FILENAME";
  ;;
    Region)
        grim -g "$(slurp)" "$FILENAME";
  ;;
    Focused)
        grim -g "$FOCUSED" "$FILENAME";
  ;;
    "4s Fullscreen")
        sleep 4s && grim "$FILENAME";
  ;;
    "4s Region")
        sleep 4s && grim -g "$(slurp)" "$FILENAME";
  ;;
    "4s Focused")
        sleep 4s && grim -g "$FOCUSED" "$FILENAME";
  ;;
    '')
        # notify-send "Screenshot" "Cancelled"
        exit 0
        ;;
    *)
      GEOMETRY="`echo \"$CHOICE\" | cut -d$'\t' -f1`"
      grim -g "$GEOMETRY" "$FILENAME";
esac

wl-copy < "$FILENAME";
notify-send "Screenshot" "File saved as <i>'$FILENAME'</i> and copied to the clipboard." -i "$FILENAME";
