---
kernel_version: "{{ ansible_facts['kernel'] }}"

WSL1: "{{ ansible_facts.kernel is regex('.*Microsoft$') }}"

WSL2: "{{ ansible_facts.kernel is regex('.*-microsoft-standard$') }}"

dotfiles_list_tmux:
  - { src: 'tmux.conf', dest: '.tmux.conf', state: 'link' }

dotfiles_list_mako:
  - { src: 'config/mako'         , dest: '.config/mako'         , state: 'hard' }

dotfiles_list:
  - { src: 'Xresources'          , dest: '.Xdefaults'           , state: 'link' }
  - { src: 'aliases'             , dest: '.aliases'             , state: 'link' }
  - { src: 'bash_profile'        , dest: '.bash_profile'        , state: 'link' }
  - { src: 'bashrc'              , dest: '.bashrc'              , state: 'link' }
  - { src: 'config/foot'         , dest: '.config/foot'         , state: 'link' }
  - { src: 'config/luakit'       , dest: '.config/luakit'       , state: 'link' }
  - { src: 'config/sway'         , dest: '.config/sway'         , state: 'link' }
  - { src: 'curlrc'              , dest: '.curlrc'              , state: 'link' }
  - { src: 'gitignore'           , dest: '.gitignore'           , state: 'link' }
  - { src: 'gnupg/gpg-agent.conf', dest: '.gnupg/gpg-agent.conf', state: 'link' }
  - { src: 'gnupg/gpg.conf'      , dest: '.gnupg/gpg.conf'      , state: 'link' }
  - { src: 'inputrc'             , dest: '.inputrc'             , state: 'link' }
  - { src: 'muttrc'              , dest: '.muttrc'              , state: 'link' }
  - { src: 'profile'             , dest: '.profile'             , state: 'link' }
  - { src: 'ripgreprc'           , dest: '.ripgreprc'           , state: 'link' }
  - { src: 'ssh_config'          , dest: '.ssh/config'          , state: 'link' }
  - { src: 'vimrc'               , dest: '.vimrc'               , state: 'link' }
  - { src: 'weechat.conf'        , dest: 'weechat.conf'         , state: 'link' }
  - { src: 'man'                 , dest: '.local/man'           , state: 'link' }

dotfiles_gitconfig_local:
  - { src: 'gitconfig', dest: '.gitconfig', state: 'link' }

dotfiles_gitconfig_remote:
  - { src: 'gitconfig-remote', dest: '.gitconfig', state: 'link' }

tmux_remove_lines:
  - "unbind C-b"
  - "set -g prefix C-Space"
  - "bind C-Space send-prefix"
  - "bind -n C-left prev"
  - "bind -n C-right next"
  - "bind > swap-pane -D"
  - "bind < swap-pane -U"
