---
- name: Check if asound.conf is present
  file:
    path: /etc/asound.conf
    state: file
    modification_time: preserve
    access_time: preserve
  register: stat_asound

- name: Backup existing asound.conf
  copy:
    remote_src: yes
    src: /etc/asound.conf
    dest: /etc/asound_conf_backup
  when: stat_asound.size > 1
  become: yes

- name: Set secondary (fallback) ALSA output system-wide
  lineinfile:
    path: /etc/asound.conf
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - "defaults.pcm.card {{ alsa_out_secondary }}"
    - "defaults.ctl.card {{ alsa_out_secondary }}"
  become: yes

- name: Check if ~/.asoundrc is present
  file:
    path: "{{ ansible_env.HOME}}/.asoundrc"
    state: file
    modification_time: preserve
    access_time: preserve
  register: stat_asoundrc

- name: Backup existing ~/.asoundrc
  copy:
    remote_src: yes
    src: "{{ ansible_env.HOME}}/.asoundrc"
    dest: "{{ ansible_env.HOME}}/asoundrc_backup"
  when: stat_asoundrc.size > 1

- name: Set primary ALSA output in ~/.asoundrc
  template:
    src: alsa.j2
    dest: "{{ ansible_env.HOME}}/.asoundrc"

- name: Reload ALSA configs
  command: alsaucm reload
  register: alsa_reloaded
  changed_when: alsa_reloaded.rc != 0
  become: yes
