---
- name: Check if asound.conf is present
  stat:
    path: /etc/asound.conf
  register: stat_asound

- name: Backup existing asound.conf
  copy:
    remote_src: yes
    src: /etc/asound.conf
    dest: "/etc/backup_asound_conf_{{ ansible_date_time.epoch }}"
  when: stat_asound | bool
  become: yes

- name: Remove existing asound.conf
  file:
    path: /etc/asound.conf
    state: absent
  become: yes

- name: Set ALSA card and device in ~/.asoundrc
  template:
    src: alsa.j2
    dest: "{{ ansible_env.HOME}}/.asoundrc"
    backup: yes

- name: Add Intel HDA parameters
  lineinfile:
    path: /etc/modprobe.d/snd-hda-intel.conf
    regexp: '^options\ snd-hda-intel\ '
    line: "options snd-hda-intel {{ intel_hda_options }}"
    state: present
  when: intel_hda_options | length > 2

- name: Reload ALSA configs
  command: alsaucm reload
  register: alsa_reloaded
  changed_when: alsa_reloaded.rc != 0
  become: yes
