- name: Parse cpuinfo
  shell:
    cmd: "grep -i vendor /proc/cpuinfo | head -1 | awk '{print $3}'"
  register: cpu_model
  changed_when: False

- name: Set facts about CPU
  set_fact:
    cpu_vendor: "{{ cpu_model.stdout_lines[0] | string }}"

- name: Disable iGFX for Intel CPU
  set_fact:
    cpu_iommu: " intel_iommu=igfx_off"
  when:
    - '"Intel" in cpu_vendor'
    - intel_disable_igfx|bool == true
