---
- name: Run sanity-checks
  import_tasks: assertions.yml
  become: yes
  tags:
    - laptop_assert

- name: Install laptop packages
  import_tasks: packages_laptop.yml
  become: yes
  tags:
    - laptop_packages

- name: Notebook-specific settings
  import_tasks: notebook.yml
  become: yes
  tags:
    - laptop_notebook

- name: Intel-specific settings
  import_tasks: intel.yml
  become: yes
  tags:
    - laptop_intel

- name: Setup ALSA
  import_tasks: alsa.yml
  when: setup_alsa
  tags:
    - laptop_alsa

- name: Configure services
  import_tasks: services.yml
  become: yes
  tags:
    - laptop_services
