---
- name: Add user to i2c group
  user:
    append: yes
    groups: i2c
    name: "{{ ansible_env.USER }}"
  when: user_add_i2c

- name: Unmask sleep and suspend systemd targets
  systemd:
    name: "{{ item }}"
    masked: no
  with_items:
    - "sleep.target"
    - "suspend.target"
    - "hibernate.target"
    - "hybrid-sleep.target"
  when: enable_sleep_hibernate

- name: Configure suspend and hibernate in logind.conf
  lineinfile:
    path: /etc/systemd/logind.conf
    line: "{{ item }}"
  with_items:
    - 'IdleAction="{{ logind_idle_action }}"'
    - 'IdleActionSec="{{ logind_idle_time }}"'
    - 'HandleLidSwitch="{{ logind_lid_action }}"'
    - 'HandlePowerKey={{ logind_powerbutton_action }}"'

- name: Configure suspend and hibernate in sleep.conf
  lineinfile:
    path: /etc/systemd/sleep.conf
    line: "{{ item }}"
  with_items:
    - 'HibernateDelaySec="{{ logind_hibernate_delay }}"'
