---
- name: Install list of packages
  apt:
    name: "{{ pkg }}"
  vars:
    pkg:
      # - at-spi2-core # Dependency for Gnome apps.
      - alsa-firmware-loaders
      - alsa-ucm-conf
      - aria2
      - bpython
      - cargo
      - dictionaries-common
      - dosfstools
      - entr
      - exfatprogs
      - ffmpeg
      - filezilla
      - firefox-esr
      - firefox-esr-l10n-en-gb
      - firmware-amd-graphics
      - firmware-iwlwifi
      - firmware-misc-nonfree
      - firmware-realtek
      - firmware-sof-signed
      - fonts-liberation
      - fonts-powerline
      - fonts-recommended
      - fonts-spleen
      - fonts-terminus
      - fonts-terminus-otb
      - fzf
      - gcolor3
      - git
      - gocryptfs
      - hunspell
      - hunspell-en-au
      - imv
      - iwd
      - keepassxc
      - laptop-mode-tools
      - libasound2-plugin-smixer
      - libglib2.0-bin # gsettings
      - libreoffice-l10n-en-gb
      - libreoffice-style-sifr
      - libvirt-bin
      - libvirt-daemon-system
      - light
      - lyx
      - mako-notifier
      - mpv
      - myspell-en-au
      - mythes-en-au
      - nmap
      - pandoc
      - pmount
      - python3-pip
      - python3-psutil
      - python3-virtualenv
      - qasmixer
      - qt5ct
      - radeontop
      - rlwrap # cht.sh dependency
      - rustc
      - socat
      - strace
      - sway
      - swaybg
      - swayidle
      - swaylock
      - syncthing
      - taskwarrior
      - timeshift
      - tor
      - torsocks
      - virt-manager
      - virt-top
      - vit
      - wavemon
      - waybar
      - wdisplays
      - weechat
      - wf-recorder
      - whois
      - wob
      - wofi
      - wordnet
      - wordnet-sense-index
      - youtube-dl
      - yubioath-desktop

- name: Install GitCola without recommended dependencies
  apt:
    name: git-cola
    state: present
    install_recommends: no

- name: Launch KeepassXC via .desktop with 1.5x scale
  lineinfile:
    path: /usr/share/applications/org.keepassxc.KeePassXC.desktop
    regexp: '^Exec=keepassx.*'
    line: Exec=env QT_SCALE_FACTOR=1.5 keepassxc %f

