---
- name: Assert that we are running against the supported distribution
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_file_variety == "Debian"
      - ansible_distribution_release == "bullseye"
      - ( ansible_distribution_major_version | int ) == 0 # TODO: Replace with "11" once Bullseye is out
    fail_msg: "This playbook is tested exclusively on Debian Bullseye.\nPlease double-check you are executing the right thing."
    success_msg: "Running against Debian Bullseye at {{ ansible_host }}"

- name: Assert that desirable hostname is valid
  assert:
    that: inventory_hostname is regex('^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$')
    fail_msg: "Requested hostname is invalid.\nSee the RFC #1123"
    success_msg: "Will set target's hostname to '{{ inventory_hostname }}'"
  when: inventory_hostname | string | length > 0
