---
- name: Register existing permissions overrides
  shell:
    cmd: 'dpkg-statoverride --list | cut -d " " -f 4'
  register: dpkg_existing_overrides
  changed_when: False
  failed_when: dpkg_existing_overrides.stdout_lines | length < 2
- set_fact:
    dpkg_existing_overrides: "{{ dpkg_existing_overrides.stdout_lines }}"

- name: Register new permissions overrides
  read_csv:
    # read_csv doesn't accept relative path for some reason
    path: "{{ role_path }}/files/conf/dpkg_overrides.csv"
    delimiter: ","
    strict: yes
  register: dpkg_overrides
  delegate_to: localhost
- set_fact:
    dpkg_overrides: "{{ dpkg_overrides | dict2items }}"
- set_fact:
    dpkg_overrides: "{{ dpkg_overrides[1].value }}"

- name: Update permissions overrides if necessary
  shell:
    cmd: "{{ 'dpkg-statoverride --update --add ' + item['user'] + ' ' + item['group'] + ' ' + item['chmod'] + ' ' + item['path'] }}"
  with_items: "{{ dpkg_overrides }}"
  when: item['path'] not in dpkg_existing_overrides
