---
- name: Purge contradictory packages
  apt:
    state: absent
    purge: yes
    autoremove: yes
    name:
    - wpasupplicant
    - rpcbind
    - exim4
    - bind9
    - avahi-daemon
    - dnsmasq
    - ntp
