---
- name: Copy /etc/ssh/sshd_config
  copy:
    src: conf/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0644
  notify:
    - restart sshd

- name: Enable less secure ciphers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Ciphers\s'
    line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-cbc"
  when: sshd_less_secure == True

- name: Enable less secure MACs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MACs\s'
    line: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha-256"
  when: sshd_less_secure == True

- name: Copy /etc/sysctl.conf
  copy:
    src: conf/sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    mode: 0644
  notify:
    - reload sysctl

- name: Copy system.conf
  copy:
    src: conf/system.conf
    dest: /etc/systemd/system.conf
    owner: root
    mode: 0644

- name: Blacklist kernel modules
  template:
    src: blacklist.j2
    dest: /etc/modprobe.d/blacklist.conf
    owner: root
    mode: 0644
  notify:
    - reboot host

- name: Modify /etc/issue
  copy:
    dest: "{{ item }}"
    content: ' '
  with_items:
    - /etc/issue
    - /etc/issue.net

- name: Change CapsLock to Ctrl
  lineinfile:
    path: /etc/default/keyboard
    insertafter: 'XKBVARIANT=""'
    regexp: '^XKBOPTIONS'
    line: 'XKBOPTIONS="caps:ctrl_modifier"'
    state: present
  notify:
    - dpkg_keyboard
  when: set_capslock and not WSL2 and not WSL1

- name: GRUB settings
  # Refs: https://github.com/Whonix/security-misc/blob/master/etc/default/grub.d/40_kernel_hardening.cfg
  #       https://tails.boum.org/contribute/design/kernel_hardening/
  #       https://kernsec.org/wiki/index.php/Kernel_Self_Protection_Project/Recommended_Settings
  lineinfile:
    path: /etc/default/grub
    # Bullseye, v5.10+
    # TODO: 
    #   - Enable `module.sig_enforce=1` once SB is operational
    #   - Consider `lockdown=confidentiality`
    #   - Consider `slub_debug=ZF`
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet kaslr apparmor=1 security=apparmor ipv6.disable=1 kernel.kptr_restrict=2 slab_nomerge mce=0 page_alloc.shuffle=1 mitigations=auto audit=0 efi=disable_early_pci_dma init_on_alloc=1 debugfs=off init_on_free=1 pti=auto vsyscall=none extra_latent_entropy{{ cpu_iommu }} fsck.mode=force fsck.repair=preen {{ grub_optional }} kernel.kexec_load_disabled=1"'
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
  notify: grub_update
  when: not WSL1 and not WSL2

- name: Tighten Grub config permissions (V-38583)
  file:
    path: "{{ item }}"
    mode: 0600
  with_items:
    - "/boot/grub/grub.cfg"
    - "/boot/grub/grubenv"
    - "/boot/grub/unicode.pf2"

- name: Adjust sudo defaults
  lineinfile:
    path: /etc/sudoers
    line: "{{ item }}"
    insertafter: "^Defaults.*"
  with_items:
    - "Defaults  requiretty"
    - "Defaults  use_pty"
    - 'Defaults  lecture="never"'
    - "Defaults  insults"

- name: Set default non-root $HOME permissions to 750
  lineinfile:
    path: /etc/adduser.conf
    line: "DIR_MODE=0750"

- name: Find existing users under /home/
  find:
    paths: /home/
    file_type: directory
    recurse: no
  register: home_dirs

- name: Set existing user home-dirs to 0750
  file:
    path: "{{ item.path }}"
    mode: 0750
  with_items: "{{ home_dirs.files }}"

- name: Disable acces to /proc in /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "proc /proc proc nosuid,nodev,noexec,hidepid=2 0 0"
    regexp: '^proc /proc .*'
    insertafter: EOF
    state: present
  when: not WSL1 and not WSL2
  notify: "reload systemd"

- block:

  - name: Mount /tmp with nodev, nosuid, and noexec
    lineinfile:
      path: /etc/fstab
      line: "tmpfs /tmp tmpfs rw,nosuid,nodev,noexec 0 0"
      regexp: '^tmpfs\s\/tmp\s.*'
      insertafter: EOF
      state: present
    when: not WSL1 and not WSL2
    notify: "reload systemd"

  - name: Mount /var/tmp with nodev, nosuid, and noexec
    lineinfile:
      path: /etc/fstab
      line: "/tmp /var/tmp none rw,noexec,nosuid,nodev,bind 0 0"
      regexp: '^\/tmp.*'
      insertafter: EOF
      state: present
    when: not WSL1 and not WSL2
    notify: "reload systemd"

  - name: Mount /dev/shm with nodev, nosuid, and noexec
    lineinfile:
      path: /etc/fstab
      line: "tmpfs /dev/shm tmpfs defaults,nosuid,nodev,noexec 0 0"
      regexp: '^tmpfs\s\/dev\/shm.*'
      insertafter: EOF
      state: present
    when: not WSL1 and not WSL2
    notify: "reload systemd"

  when: fstab_noexec

- name: Harden rsync systemd module
  blockinfile:
    path: /usr/lib/systemd/system/rsync.service
    block: |
      ProtectSystem=full
      PrivateDevices=on
      NoNewPrivileges=on
    insertafter: "^ExecStart.*"
  when: not WSL1 and not WSL2

- name: Make systemd-journal volatile
  lineinfile:
    path: /etc/systemd/journald.conf
    line: "Storage=volatile"
    insertafter: "[Journal]"
    state: present

- name: Ensure /etc/systemd/coredump.conf.d exists
  file:
    path: /etc/systemd/coredump.conf.d
    state: directory

- name: Instruct systemd to avoid preserving coredumps
  copy:
    dest: /etc/systemd/coredump.conf.d/custom.conf
    content: "[Coredump]\nStorage=none\n"

- name: Set zero limit to prevent dumps from being written to disk
  lineinfile:
    path: /etc/security/limits.conf
    line: "* hard core 0"
    insertbefore: '^#\ End\ of\ file'
    firstmatch: yes
    state: present

- name: Prevent applications with setuid from dumping their memory
  copy:
    dest: /etc/sysctl.d/suid_dumpable.conf
    content: "fs.suid_dumpable=0"

- name: Add 2s. delay to failed login attempts
  copy:
    dest: /etc/pam.d/system-login
    content: "auth optional pam_faildelay.so delay=2000000"

- name: Block unnecessary network protocols
  copy:
    src: conf/uncommon-network-protocols.conf
    dest: /etc/modprobe.d/uncommon-network-protocols.conf

- name: Enable APT sandboxing
  copy:
    dest: /etc/apt/apt.conf.d/02sandboxing
    content: 'APT::Sandbox::Seccomp "true";'

- name: Configure APT
  lineinfile:
    dest: /etc/apt/apt.conf.d/03settings
    mode: 0644
    state: present
    create: 'yes'
    line: "{{ item }}"
  with_items:
    - 'APT::ExtractTemplates::TempDir "~/.cache/apt";'
    - 'APT::Get::AllowUnauthenticated "false";'
    - 'APT::Periodic::AutocleanInterval "2";'
    - 'Acquire::AllowTLS "true";'
    - 'Acquire::ForceIPv4 "true";'
    - 'Acquire::http::AllowRedirect "false";'
    - 'Acquire::http::Timeout "10";'
    - 'Acquire::https::AllowRedirect "false";'
    - 'Acquire::https::Timeout "10";'
    - 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
