---
- name: Copy /etc/ssh/sshd_config
  copy:
    src: conf/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0644
  notify:
    - restart sshd

- name: Enable less secure ciphers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Ciphers\s'
    line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-cbc"
  when: sshd_less_secure == True

- name: Enable less secure MACs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MACs\s'
    line: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha-256"
  when: sshd_less_secure == True

- name: Copy /etc/sysctl.conf
  copy:
    src: conf/sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    mode: 0644
  notify:
    - reload sysctl

- name: Copy system.conf
  copy:
    src: conf/system.conf
    dest: /etc/systemd/system.conf
    owner: root
    mode: 0644

- name: Copy blacklist.conf
  copy:
    src: conf/blacklist.conf
    dest: /etc/modprobe.d/blacklist.conf
    owner: root
    mode: 0644

- name: Disable pc-speaker (don't beep)
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "blacklist pcspkr"
  when: disable_speaker

- name: Modify /etc/issue
  copy:
    dest: "{{ item }}"
    content: 'Access to this computer is prohibited.\n\n'
  with_items:
    - /etc/issue
    - /etc/issue.net

- name: Change CapsLock to Ctrl
  lineinfile:
    path: /etc/default/keyboard
    insertafter: 'XKBVARIANT=""'
    regexp: '^XKBOPTIONS'
    line: 'XKBOPTIONS="caps:ctrl_modifier"'
    state: present
  notify:
    - dpkg_keyboard
  when: not WSL2 and not WSL1

- name: GRUB settings
  # Refs: https://github.com/Whonix/security-misc/blob/master/etc/default/grub.d/40_kernel_hardening.cfg
  #       https://tails.boum.org/contribute/design/kernel_hardening/
  lineinfile:
    path: /etc/default/grub
    # Buster, v4.19+
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet kaslr  apparmor=1 security=apparmor ipv6.disable=1 kernel.kptr_restrict=2 kernel.kexec_load_disabled=1 slab_nomerge slub_debug=FZP mce=0 page_poison=1 mitigations=auto,nosmt audit=0 efi=disable_early_pci_dma init_on_alloc=1 init_on_free=1 pti=on module.sig_enforce=1 vsyscall=none extra_latent_entropy{{ cpu_iommu }}"'
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
  notify: grub_update
  when: not WSL1 and not WSL2

- name: Disable acces to /proc in /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "proc /proc proc nosuid,nodev,noexec,hidepid=2 0 0"
    insertafter: EOF
    state: present
  when: not WSL1 and not WSL2

- name: Check root FS on every boot
  file:
    path: /forcefsck
    state: touch
    modification_time: preserve
    access_time: preserve
  become: yes

- name: Make systemd-journal volatile
  lineinfile:
    path: /etc/systemd/journald.conf
    line: "Storage=volatile"
    insertafter: "[Journal]"
    state: present

- name: Ensure /etc/systemd/coredump.conf.d exists
  file:
    path: /etc/systemd/coredump.conf.d
    state: directory

- name: Instruct systemd to not store coredumps
  copy:
    dest: /etc/systemd/coredump.conf.d/custom.conf
    content: "[Coredump]\nStorage=none\n"

- name: Set zero limit to prevent dumps from being written to disk
  lineinfile:
    path: /etc/security/limits.conf
    line: "* hard core 0"
    insertbefore: '^#\ End\ of\ file'
    firstmatch: yes
    state: present

- name: Prevent applications with setuid from dumping their memory
  copy:
    dest: /etc/sysctl.d/suid_dumpable.conf
    content: "fs.suid_dumpable=0"

- name: Add 2s. delay to failed login attempts
  copy:
    dest: /etc/pam.d/system-login
    content: "auth optional pam_faildelay.so delay=2000000"

- name: Block unnecessary network protocols
  copy:
    src: conf/uncommon-network-protocols.conf
    dest: /etc/modprobe.d/uncommon-network-protocols.conf

- name: Enable APT sandboxing
  copy:
    dest: /etc/apt/apt.conf.d/02sandboxing
    content: 'APT::Sandbox::Seccomp "true";'
