---
- name: Set default locale to "{{ locale }}"
  debconf:
    name: locales
    question: locales/default_environment_locale
    value: "{{ locale }}"
    vtype: select

- name: Generate locales
  debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: en_US.UTF-8 UTF-8, "{{ locale }}" UTF-8
    vtype: multiselect

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Enable systemd-timesyncd service
  service:
    name: systemd-timesyncd
    enabled: true
    state: started
  when: not WSL1 and not WSL2

- name: Copy /etc/systemd/timesyncd.conf
  copy:
    src: conf/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: preserve
  when: not WSL1 and not WSL2
  notify:
    - restart timesyncd
