---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Disable ipv6
  lineinfile:
    path: /etc/ufw/ufw.conf
    line: "IPV6=no"
    insertafter: EOF

- name: Don't autoconfigure ipv6
  # Note: single-quoted for a reason
  replace:
    path: /etc/ufw/sysctl.conf
    regexp: '^#(net\/ipv6\/conf\/\w*\/autoconf\=0)'
    replace: '\1'

- name: Limit SSH connections
  ufw:
    rule: limit
    port: ssh
    proto: tcp
    comment: Limit SSH via Ansible
  when: allow_ssh

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming
    logging: 'off'

- name: Ensure UFW is up and running
  service:
    name: ufw
    state: restarted
  changed_when: False
