---
- name: Assert that supplied data is valid
  assert:
    that:
      - wg_server_ip | ipaddr
      - wg_port | int > 1
      - wg_iface | length > 1

- name: Install wireguard
  apt:
    name: "{{ pkg }}"
    state: present
  vars:
    pkg:
      - wireguard
      - wireguard-tools

- name: Enable routing in sysctl
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward=1"
    state: present
  when: wg_forward

- name: Check if there is an existing config
  find:
    paths: /etc/wireguard
    patterns: '*.conf'
    size: 2
  register: wg_existing_conf

- name: Assert there are no usable configs present
  set_fact:
    wg_configured: true
  when: wg_existing_conf.files | length > 0

- name: Create private/public keypair
  shell:
    chdir: /etc/wireguard
    cmd: wg genkey | tee privatekey | wg pubkey > publickey
  when: not wg_configured

- name: Register private key
  slurp:
    src: "/etc/wireguard/privatekey"
  register: wg_privkey

- name: Register public key
  slurp:
    src: "/etc/wireguard/publickey"
  register: wg_pubkey

- name: Verify that both keys are of expected length
  set_fact:
    wg_keys_valid: true
  when: wg_pubkey['content'] | length == 60 and wg_privkey['content'] | length == 60

- name: Create core of the Wireguard configuration file
  template:
    src: wireguard.j2
    dest: "/etc/wireguard/{{ wg_iface }}.conf"
    owner: root
    mode: 0600
  register: wg_configured
  when: wg_keys_valid

- name: Enable forwarding in UFW's sysctl settings
  replace:
    path: "/etc/ufw/sysctl.conf"
    regexp: '^#(net\/ipv4\/ip_forward\=1)'
    replace: '\1'
  when: wg_keys_valid

- name: Change default UFW forward policy to ACCEPT
  lineinfile:
    path: "/etc/default/ufw"
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
    regexp: '^DEFAULT_FORWARD_POLICY'
  when: wg_keys_valid

- name: Enable Wireguard systemd service, but don't start it
  systemd:
    name: "wg-quick@{{ wg_iface }}.service"
    enabled: yes
    masked: no
    state: stopped

- name: Re-read systemd settings
  systemd:
    daemon_reload: yes

- name: Reload systemd
  systemd:
    daemon_reexec: yes


- name: TODO Deploy clients


- name: Start Wireguard daemon
  systemd:
    name: "wg-quick@{{ wg_iface }}.service"
    state: started
    enabled: yes



